services:
  server2:
## <--common
    profiles: [all, "${CONTNAME}"]
    restart: unless-stopped
    security_opt:
    - no-new-privileges:true
    environment:
      - GLOBALVAR1=${GLOBALVAR1}
      - GLOBALVAR2=${GLOBALVAR2}
      - LOCALVAR1=${LOCALVAR1}
      - LOCALVAR2=${LOCALVAR2}
      - CONTNAME=${CONTNAME}
## <--container specific
    container_name: ${CONTNAME}
    image: nested-var-compose
    ports:
      - '8102:8080'
    labels:
      - homepage.group=${GLOBALVAR1}
      - homepage.name=${LOCALVAR1}
      - homepage.icon=${LOCALVAR2}
      - homepage.href=${GLOBALVAR1}
      - homepage.description=${LOCALVAR2}
   #command: printenv GLOBALVAR1 GLOBALVAR2 LOCALVAR1 LOCALVAR2

