include: 
  - ./base-config.yaml
services:
  server3:
## <--common
    <<: *base-service
    profiles: [all, "${CONTNAME}"]
    environment:
      - GLOBALVAR1=${GLOBALVAR1}
      - GLOBALVAR2=${GLOBALVAR2}
      - LOCALVAR1=${LOCALVAR1}
      - LOCALVAR2=${LOCALVAR2}
      - CONTNAME=${CONTNAME}
## <--container specific
    container_name: ${CONTNAME}
    image: nested-var-compose
    ports:
      - '8103:8080'
    labels:
      - homepage.group=${GLOBALVAR1}
      - homepage.name=${LOCALVAR1}
      - homepage.icon=${LOCALVAR2}
      - homepage.href=${GLOBALVAR1}
      - homepage.description=${LOCALVAR2}
   #command: printenv GLOBALVAR1 GLOBALVAR2 LOCALVAR1 LOCALVAR2

